# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Gradle@2
            displayName: Build the app
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'build'
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              repository: $(imageName)
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                latest
                $(tag)
          - task: Docker@2
            displayName: Push image to docker hub
            inputs:
              containerRegistry: |
                $(dockerHub)
              repository: $(imageName)
              command: push
              tags: |
                latest
                $(tag)
          - task: AzureAppServiceManage@0
            displayName: Restart the web app
            inputs:
              azureSubscription: 'Pay-As-You-Go(bcbd3faa-a503-4f9a-88ef-1e66b902964c)'
              Action: 'Restart Azure App Service'
              WebAppName: 'idayms'